# Generated by Django 2.2.28 on 2023-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.TextField(choices=[('new', 'New'), ('doing', 'Doing'), ('revision', 'Revision'), ('done', 'Done')], default='new'),
        ),
    ]
